### ISSUE TITLE
URGENT: Great package, your myutil.py script not included in pip/git version

### ISSUE THREAD

**Issue by jmarsil** [Jingnan-Jia/segmentation_metrics#1]
<img width="1153" alt="Screen Shot 2020-11-04 at 12 06 47 PM" src="https://user-images.githubusercontent.com/39134049/98142871-61d1d000-1e96-11eb-944a-e024e14f0ea5.png">

**Comment by Jingnan-Jia** [comment]
Sorry for the late reply. I fixed this issue. Please download the newest version.
