### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by francismontalbo** [Jingnan-Jia/segmentation_metrics#13]
Hello, I installed the package already but when I import it I get an error 

No module named 'seg_metrics'

**Comment by Jingnan-Jia** [comment]
`pip install seg-metrics`

**Comment by Jingnan-Jia** [comment]
Hi, can you ensure you successfully install the package by the following command?

`pip install seg-metrics`

Could you please check if the module is installed in your current environment ("pip list" will show all the installed packages in the current environment)

**Comment by Jingnan-Jia** [comment]
![image](https://user-images.githubusercontent.com/34941987/149661782-caf0129c-6c7f-48f8-bc3d-afa3a9603396.png)

This screenshot shows how it works in my environment.

**Comment by francismontalbo** [comment]
Yes, it is successfully installed on my pip list. But it won't import with 'seg_metrics'

**Comment by Jingnan-Jia** [comment]
![image](https://user-images.githubusercontent.com/34941987/149664637-3dfc899d-3583-44e3-9a89-a488ba4f3b33.png)

It seems very weird. Because I tried it on my google Colab and it works. 

Can you uninstall and install it again ? Also make sure the version is the latest.
Or can you provide more details so that I can reproduce it?

**Comment by francismontalbo** [comment]
I find it weird as well. I don't know why its not being found.

![image](https://user-images.githubusercontent.com/65653238/149705541-33d4afc4-171d-4e2a-a89f-55a81e1e51bb.png)

**Comment by Jingnan-Jia** [comment]
It would be better if you can let others reproduce your issue. I can not reproduce your issue. I guess it is because of your environment. I advise you to create a new clean environment and install the package again.
