### ISSUE TITLE
Unit of Volume Similarity 

### ISSUE THREAD

**Issue by monjoybme** [Jingnan-Jia/segmentation_metrics#21]
Could you please tell me what will be the unit of Volume Similarity? Is that mm3? Do you have any reference material?
Thanks!

**Comment by Jingnan-Jia** [comment]
Hi @monjoybme , 

The volume similarity has no unit. It is a ratio defined as: $2∗(v1−v2)/(v1+v2)$

The defination and example could be found [here](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/34_Segmentation_Evaluation.html) (You could search “GetVolumeSimilarity” in the page)

**Comment by monjoybme** [comment]
Thanks! What does it mean if volume similarity is negative and positive?

**Comment by Jingnan-Jia** [comment]
@monjoybme Sorry for the late reply. Please check [this page](https://github.com/Jingnan-Jia/segmentation_metrics/blob/master/README_appendix.md#explanication-of-volume-similarity) for the meaning of volume similarity.

**Comment by monjoybme** [comment]
Thanks!
