### ISSUE TITLE
Evaluation metric  3D or 2D based segmentation 

### ISSUE THREAD

**Issue by Merom99** [Jingnan-Jia/segmentation_metrics#27]
Hi, 

If I used 2D configuration for a volumetric image, is the evaluation metric computed for the 3D volume or per 2D slices and then aggregating?

Thanks

**Comment by Jingnan-Jia** [comment]
@Merom99 Hi Merom99, can you clarify what do you mean for "used 2D configuration for a volumetric image"? Currently, the package does not aggregate 2D slices to 3D. If the images are a batch of 2D/3D images, then the results would be the metrics of all 2D/3D images.
