### ISSUE TITLE
Potential Documentation Optimization

### ISSUE THREAD

**Issue by jinggqu** [Jingnan-Jia/segmentation_metrics#29]
Thank you for this wonderful work.

The indication of whether the return value of `sg.write_metrics()` is a `list` or a `dict` is only present in the [README](https://github.com/Jingnan-Jia/segmentation_metrics#:~:text=the%20same%20directory.-,Note%3A,-When%20evaluating%20one). In this case, would you mind making the return type clearer in the [documentation](https://github.com/Jingnan-Jia/segmentation_metrics/blob/df9a231275decb7803ed8e16792ccd3ab9300d28/seg_metrics/seg_metrics.py#L280C5-L280C59) ?

Thanks.

**Comment by Jingnan-Jia** [comment]
@jinggqu Thank you for your suggestions. I updated the package. By installing the latest version you can have the clearer documentation.
