### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'Array'

### ISSUE THREAD

**Issue by barzan-hayati** [Jingnan-Jia/segmentation_metrics#3]
by importing `seg_metrics` 

`import seg_metrics.seg_metrics as sg`

it gives me this error

`AttributeError: module 'numpy' has no attribute 'Array'
` at [def computeQualityMeasures(lP: np.Array, lT: np.Array, spacing: np.Array, metrics_type=None):](https://github.com/Jingnan-Jia/segmentation_metrics/blob/7d0064d88c7c8057c8470d085601c4e72aad54b2/seg_metrics/seg_metrics.py#L24)

**Comment by Jingnan-Jia** [comment]
Hi, thanks for your issue. This bug is already fixed now. Please try to uninstall and install the package again.
