### ISSUE TITLE
Questions about Spacing

### ISSUE THREAD

**Issue by wangtongy** [Jingnan-Jia/segmentation_metrics#32]
Hi, Jingnan, 

Thank you for sharing this repository. 

I do have a question regarding to `spacing` in the input. Is it the same spacing between pixels? That leads to a specific question about the HD unit. Is it in pixels or mm (saying if my spacing is in mm)? 

Thanks!

**Comment by Jingnan-Jia** [comment]
Sorry for the late reply. Yes, the spacing is the distance between pixels (or voxels in 3D images). The unit of spacing is `mm`
