### ISSUE TITLE
 Long Execution Time for 3D Image Processing in Latest Version

### ISSUE THREAD

**Issue by BME-Jafar** [Jingnan-Jia/segmentation_metrics#33]
I noticed that when using the latest version of the code, it took up to 40 minutes to generate 13 3D images, particularly when including Dice computation. I also replicated this issue using the provided example notebook, and the execution time was similarly long.

However, when reverting to version 1.2.7, the execution time returned to normal.

Could you please investigate this performance issue in the latest version?

**Comment by Jingnan-Jia** [comment]
@BME-Jafar Thank you for raising this issue. In the 1.2.8, I re-wrote the method of volume similarity. I guess this is the reason. If you do not need volume similarity you can just explicitly specify to use dice and hd95 and msd, etc.  

In the future days, I will research how to accelerate the calculation of volume similarity. Thank you again.

**Comment by BME-Jafar** [comment]
Thank you, @Jingnan-Jia, that makes sense! I appreciate the update and your work.
