### ISSUE TITLE
TypeError: 'type' object is not subscriptable, line 144

### ISSUE THREAD

**Issue by AustinTapp** [Jingnan-Jia/segmentation_metrics#4]
Dear Jingnan-Jia,

When running the code:

import seg_metrics.seg_metrics as sg

def main():
    labels = [0, 4, 5, 6, 7, 8]
    gdth_file = 'data/MyImage.nii.gz'
    pred_file = 'data/MyImage2.nii.gz'
    csv_file = 'metrics.csv'

    metrics = sg.write_metrics(labels=labels[1:],  # exclude background
                               gdth_path=gdth_file,
                               pred_path=pred_file,
                               csv_file=csv_file)
    print(metrics)

if __name__ == '__main__':
    main()

The following error is reported:

Traceback (most recent call last):
  File ".../ImageMetricEval.py", line 1, in <module>
    import seg_metrics.seg_metrics as sg
  File "...\lib\site-packages\seg_metrics\seg_metrics.py", line 144, in <module>
    def get_metrics_dict_all_labels(labels, gdth, pred, spacing, metrics_type=None) -> dict[str, list]:
TypeError: 'type' object is not subscriptable

When possible, please let me know how to correct this issue. Thank you for your support.

Best regards,
Austin

**Comment by AustinTapp** [comment]
Apologies, the code posted was incorrectly formatted after submitting this issue. Please see the screenshot.

Thanks,
Austin
![ErrorScreenshot](https://user-images.githubusercontent.com/29557420/130155807-99cbcdc1-2802-4437-93ea-ae74b237d6db.PNG)

**Comment by Jingnan-Jia** [comment]
Hi Austin,

Sorry I was on my vacation in the past month. I fixed this issue. Please download the latest package (`pip install seg-metrics --upgrade`). Thanks again for your interest. Please let me know if you more questions.
